[tool.poetry]
name = "matchescu-base"
version = "0.27.7"
description = "Base abstract data types for Entity Resolution"
authors = ["Andrei Olar <andrei.olar@ubbcluj.ro>"]
readme = "README.md"
packages = [{include="matchescu", from="src"}]

[tool.poetry.dependencies]
python = "!=3.14.1,~3.13"
networkx = "^3.6.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
mypy = "^1.20.2"
black = "^25.12.0"
ruff = "^0.16.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
